inherit_from:
  - .rubocop_todo.yml
  - config/rubocop/rubocop.yml
  - config/rubocop/rails.yml
  - config/rubocop/rspec.yml

require:
  - rubocop-rails
  - rubocop-rspec



AllCops:
  TargetRubyVersion: 2.7
